_wandb:
    value:
        cli_version: 0.21.0
        e:
            zayasjt9fjc43h2du4gdrkz8bz5deze8:
                codePath: scripts\train_simple_vqvae.py
                codePathLocal: scripts\train_simple_vqvae.py
                cpu_count: 6
                cpu_count_logical: 6
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "499229937664"
                        used: "461400907776"
                email: drrcld01l11c351k@studium.unict.it
                executable: C:\Users\Claudio\AppData\Local\Programs\Python\Python39\python.exe
                gpu: NVIDIA GeForce RTX 2070 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2070 SUPER
                      uuid: GPU-01c646fc-a228-7dc2-a2ab-41d83ff40b77
                host: DESKTOP-VVU740H
                memory:
                    total: "17111175168"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\Claudio\Desktop\Tesi VQVAE 1\scripts\train_simple_vqvae.py
                python: CPython 3.9.13
                root: C:\Users\Claudio\Desktop\Tesi VQVAE 1
                startedAt: "2025-08-07T17:25:21.093076Z"
                writerId: zayasjt9fjc43h2du4gdrkz8bz5deze8
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 1
                - 5
                - 51
                - 53
            "2":
                - 1
                - 5
                - 51
                - 53
            "3":
                - 2
                - 3
                - 13
                - 16
            "4": 3.9.13
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 32
commitment_cost:
    value: 0.25
embedding_dim:
    value: 64
learning_rate:
    value: 0.0003
max_epochs:
    value: 100
model_type:
    value: CalciumVQVAE
num_embeddings:
    value: 512
num_hiddens:
    value: 128
num_neurons:
    value: 30
num_residual_hiddens:
    value: 32
num_residual_layers:
    value: 2
patience:
    value: 10
stride:
    value: 10
window_size:
    value: 50
